### ISSUE TITLE
Instalovaný joystick se zachytává v extrémních polohách

### ISSUE THREAD

**Issue by mordae** [mordae/krecek#5]
Když dojedu až do krajní polohy, joystick se tam uchytí a musím ho aktivně vrátit zpět. Tedy se nevycentruje sám.
Možná to není úplně problém, protože v ideálním případě by měl být limitovaný pouzdrem.

**Comment by Rafailek** [comment]
myslíš si že to je spíš kvůli tomu joysticku a ne že by to byla naše vina?

**Comment by mordae** [comment]
> myslíš si že to je spíš kvůli tomu joysticku a ne že by to byla naše vina?

Určitě je to naše vina. Neměli jsme si ho tam nechat instalovat od JLC, když jich mám doma plný pytel. :-)

**Comment by mordae** [comment]
Tak je to běžné. Prostě bychom mu neměli dovolit jít tak daleko. V každém případě v příští revizi použijeme jiný a nebudeme ho tam nechávat instalovat JLC.
